### ISSUE TITLE
Hot water setting

### ISSUE THREAD

**Issue by gradius-v** [Neuroquila-n8fall/JunkersControl#1]
I just tried this on my Junkers ZWN 18-6. Seems to work alright except the hot water stays cold.
I couldn't find a setting in the code. Can this be added ?

Thanks

**Comment by Neuroquila-n8fall** [comment]
Uh oh - sorry for not noticing this issue...! Since I'm not using the hot water on mine I can't verify it but these are the IDs related to hot water:
0x253 - Hot Water setpoint (0.5° steps so 40° are represented as value 80). 
0x255 - Hot Water Setpoint (0.5° steps so 40° are represented as value 80). 
0x203 - Current hot water temperature (0.5° steps)
0x204 - Hot Water maximum temperature (set on the heating control panel via dial, 0.5° steps)

**Comment by Neuroquila-n8fall** [comment]
Closed due to inactivity or missing feedback.

**Comment by gradius-v** [comment]
When I hook up a TA 300 Controller hot water works immediately. It sets 0x253 to 0 and 0x255 to 140 no matter what.
With these values JunkersControl works well too.
I have never logged a 0x204 message. Maybe this ist just for water tanks, I use continuous flow.

**Comment by Neuroquila-n8fall** [comment]
> When I hook up a TA 300 Controller hot water works immediately. It sets 0x253 to 0 and 0x255 to 140 no matter what. With these values JunkersControl works well too. I have never logged a 0x204 message. Maybe this ist just for water tanks, I use continuous flow.

This is very likely as described since there are separate messages that work in conjunction with other messages depending on the use case. 
So. to summarize, can I note that 0x255 is in fact the setpoint for hot water when using continuous flow setups?

**Comment by gradius-v** [comment]
Yes, and it's always to the max. value of 140 (70°C) for my model. I haven't tried other values as that is what the original controller sets no matter what.
0x202 is max continuous flow temperature as set by the dial on the device
0x203 is current continuous flow temperature

**Comment by Neuroquila-n8fall** [comment]
Thanks again for your input. This has been built into the development branch.
