### ISSUE TITLE
esp_littlefs --> failed

### ISSUE THREAD

**Issue by dossidr** [Neuroquila-n8fall/JunkersControl#42]
after build priject and upload an Error is getting:
pen(): /littlefs/configuration.json does not exist, no permits for creation
Configuration file could not be found. Please upload it first.

could anybody support me or what is the reason?
wrong environment on Visual Code and PIO?

Im woundering after upload log is getting AP Mode but can't connect to http://cerasmarter

best regards

denny

**Comment by Neuroquila-n8fall** [comment]
So first of all you have to upload the program and after that you have to upload the filesystem image. After that it should work. Make sure that the configuration.json file is present. The environment has no effect on that file.

When the MCU starts the first time it may fail to access the filesystem because it will be formatted. Upload the filesystem image again if that's the case.

When this doesn't work, show me your project file structure. Might have to tweak things manually in edge cases.

**Comment by Neuroquila-n8fall** [comment]
I forgot to add: If you can access the AP you can access the WebUi and upload the configuration file manually (this is what I wrote in the docs). 
Find the template here: [configuration.json](https://github.com/Neuroquila-n8fall/JunkersControl/blob/master/assets/Templates/Configurations/configuration.json)

**Comment by dossidr** [comment]
Hi Dave

yes i know. And today i have found the process handle and install filesystem w VSCode and Platform IO.
But my problem is the wrong CAN hardware 8Mhz. And i mean the ESP32 w/ flashed code is very slow and not so stable to be store any setup parameter per WEBUI.

And the next is... i have installed the configuration.json and flash it but the device is getting empty Setup parameter and also the "true" flag for homeassitant is setting true but nothing connected. MQTT is working.

i will forward tested after installed 16Mhz clock MCP2515.

best regards denny

**Comment by Neuroquila-n8fall** [comment]
Hi again and sorry for the late reply. The Home Assistant flag is not ready yet. It is part of the auto discovery and configuration feature which I haven't finished yet. Leave that off for now because it may induce side effects which are out of scope right now.
From another discussion it came up that setting this flag will disable the web UI somehow; just to emphasize on this ;) 

I tried the 8MHz setting as well as the 16MHz setting and both of them work contrary to my statements before where I thought it will only run on 16MHz. Nonetheless to me it appears as if something is off with your module in general since in my environment using Devkits v2 and v3, it may tike a while to load but then everything is quite responsive. A bad WiFi signal is most common for bad performance. Even though I have like -50dB on mine (productive, not lab) it is somewhat slow. The WiFi on these SoCs is not the best since the antenna is so small.

**Comment by dossidr** [comment]
Hi Dave
thanks for information.... but my solution is another.... the hardware base is also ESP32 but im using an arduino mapping code handle HEX Datastream to MQTT. It's universal CAN HEX Data mapping to MQTT. And after them im decrypt in Node-red my values... as well...Why... Homeassitant is not my favorite... im using in background IOBroker but all handle and visualizing get use my Homekit. In between im implement an Matlab Simuloink Model on Raspberry PI to be handle HEX Data. But these is not stable running and many time will be disconnect and stop working transfer and connection MQTT. So my opinion is the ESP or any other embedded controller is the best and stable working... So the only one thing is the current monitoring function w/o control the Junkers values by bidirectional as fallback on CAN Bus to BM1. So for me is only monitoring the solution because handle all setup parameter by the TA250 directly and on the Junkers Cerasmart Board as MAX Values set. I think for additional full control w/ ESP32 need disconnect TA250 otherwise the CAN values are overwritten and get any failure on Cerasmart controller......best regards denny

**Comment by Neuroquila-n8fall** [comment]
Yes that's right. You can't use the TA2xx controllers in tandem with the ESP solution. I don't really understand your current approach and why it's hindering you from throwing out the TA250.

**Comment by Neuroquila-n8fall** [comment]
It's been almost one year without response. I'll close it therefore.
