### ISSUE TITLE
lovelace UI file missing

### ISSUE THREAD

**Issue by rene-dev** [Neuroquila-n8fall/JunkersControl#5]
Hi,
Thanks for this great project! Im trying to use it on my heater, but noticed you did not include the lovalace UI file for homeasisst.
can you please upload the yaml file? I tired recreating it, but cant make it look as nice as yours.

**Comment by Neuroquila-n8fall** [comment]
I did not include it on purpose since other third party components are required for it and the entities might vary heavily.
But here it is anyways. Enjoy!
[Lovelace-Heating-Control.yaml.txt](https://github.com/Neuroquila-n8fall/JunkersControl/files/7813834/Lovelace-Heating-Control.yaml.txt)
You will need the `mini-graph-card` component and also the `bar-card`
